apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: ingress-demo
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: note-app.hk.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: note-app-service
                port:
                  number: 80

    - host: quiz.hk.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quiz-app-service
                port:
                  number: 80
